import { test, expect } from "@playwright/test"
import data from "../../data.json" with { type: "json" }

test("login, content-derived collections, preview, save, upload and restore", async ({ page, context }) => {
  await page.goto("/admin")
  await page.getByLabel("Username", { exact: true }).fill("browser-test-admin")
  await page.getByLabel("Password", { exact: true }).fill("browser-test-password-long")
  await page.getByRole("button", { name: "Log in", exact: true }).click()
  await expect(page.getByRole("button", { name: "Log out" })).toBeVisible()
  const original = await page.evaluate(async () => (await fetch("/api/admin/content")).json())
  const initialMedia = await page.evaluate(async () => (await fetch("/api/admin/media")).json())
  try {
    await page.locator("summary").filter({ hasText: /^Services$/ }).click()
    await expect(page.getByRole("group", { name: `Services (${data.services.length})`, exact: true })).toBeVisible()
    await page.getByRole("button", { name: "Add Services item", exact: true }).click()
    const services = page.getByRole("group", { name: `Services (${data.services.length + 1})`, exact: true })
    await expect(services).toBeVisible()
    if (data.services.length > 1) {
      await page.getByRole("button", { name: "Move services 2 up", exact: true }).click()
      await expect(services.locator(":scope > .admin-item").first().getByRole("textbox", { name: "Title", exact: true })).toHaveValue(data.services[1].title)
      await page.getByRole("button", { name: "Move services 1 down", exact: true }).click()
    }
    page.once("dialog", dialog => dialog.accept())
    await services.locator(":scope > .admin-item").last().getByRole("button", { name: "Remove", exact: true }).first().click()
    await expect(page.getByRole("group", { name: `Services (${data.services.length})`, exact: true })).toBeVisible()
    await page.locator("summary").filter({ hasText: /^Hero$/ }).click()
    await page.getByRole("textbox", { name: "Heading", exact: true }).fill(`${original.content.hero.heading} Preview`)
    await expect(page.getByText("Unsaved changes", { exact: true })).toBeVisible()
    await page.getByRole("button", { name: "Preview changes" }).click()
    await expect(page.frameLocator("iframe").getByRole("heading", { level: 1 })).toHaveText(`${original.content.hero.heading} Preview`)
    await page.getByRole("button", { name: "Save changes" }).click()
    await expect(page.getByRole("status")).toContainText("Saved")
    await page.goto("/")
    await expect(page.getByRole("heading", { level: 1 })).toHaveText(`${original.content.hero.heading} Preview`)
    await page.goto("/admin")
    await expect(page.getByRole("button", { name: "Log out" })).toBeVisible()
    await page.getByLabel("Upload image").setInputFiles({ name: "test.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQAAAABJRU5ErkJggg==", "base64") })
    await expect(page.getByRole("status")).toContainText("Uploaded /media/")
    await expect(page.getByLabel("Media path").last()).toHaveValue(/\/media\/.*\.png/)
    page.on("dialog", dialog => dialog.accept())
    await page.getByRole("button", { name: "Restore", exact: true }).first().click()
    await expect(page.getByRole("status")).toContainText("Version restored")
    await page.screenshot({ path: "artifacts/admin-editor-desktop.png", fullPage: true })
    await page.setViewportSize({ width: 390, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
    await page.screenshot({ path: "artifacts/admin-editor-mobile.png", fullPage: true })
    await page.goto("/")
    await expect(page.getByRole("heading", { level: 1 })).toHaveText(original.content.hero.heading)
  } finally {
    const session = await (await context.request.get("/api/admin/session")).json()
    const current = await (await context.request.get("/api/admin/content")).json()
    const media = await (await context.request.get("/api/admin/media")).json()
    await context.request.post("/api/admin/save", { headers: { Origin: "http://127.0.0.1:4317", "X-CSRF-Token": session.csrf }, data: { content: original.content, revision: current.revision, remove: media.filter((x: any) => !initialMedia.some((old: any) => old.path === x.path)).map((x: any) => x.path) } })
  }
})

for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }]) test(`public design and navigation at ${viewport.width}px`, async ({ page }) => {
  await page.setViewportSize(viewport)
  await page.goto("/")
  await expect(page.getByRole("heading", { level: 1 })).toHaveText(data.hero.heading)
  await expect(page.locator("#services article")).toHaveCount(data.services.filter(x => x.enabled).length)
  await expect(page.locator("#work")).toHaveCount(data.sections.projects ? 1 : 0)
  const navigation = data.navigation.filter(link => link.enabled && data.sections[link.section as keyof typeof data.sections])
  if (viewport.width < 768 && navigation.length) await page.getByRole("button", { name: data.accessibility.openMenu, exact: true }).click()
  const nav = page.getByRole("navigation", { name: viewport.width < 768 ? data.accessibility.mobileNav : data.accessibility.primaryNav, exact: true })
  for (const link of navigation) await expect(nav.getByRole("link", { name: link.label, exact: true })).toHaveAttribute("href", link.href)
  if (viewport.width < 768 && navigation.length) await page.getByRole("button", { name: data.accessibility.closeMenu, exact: true }).click()
  if (data.studio.showEmail) await expect(page.locator("#contact a[href^='mailto:']")).toHaveAttribute("href", `mailto:${data.studio.email}?subject=${encodeURIComponent(data.contact.subject)}&body=${encodeURIComponent(data.contact.emailBody)}`)
  if (data.studio.showWhatsapp) await expect(page.locator("#contact a[href^='https://wa.me/']")).toHaveAttribute("href", `https://wa.me/${data.studio.whatsappNumber.replace(/\D/g, "")}?text=${encodeURIComponent(data.studio.whatsappMessage)}`)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.screenshot({ path: `artifacts/admin-public-${viewport.width}.png`, fullPage: true })
})
